apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-app
  namepsace: default
spec:
  project: default
  source:
    repoURL: https://github.com/akashtamhankar/argo-cd.git
    targetRevision: HEAD
    path: environments/staging/app1 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
   automated:
    prune: true
    selfHeal: true
   syncOptions:
           - Validate=true
           - CreateNamespace=false
           - PrunePropagationPolicy=foreground
           - PruneLast=true

