apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-deployment
  namespace: bar
  labels:
    app: bar
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: akashtamhankar/website:v6
        ports:
        - containerPort: 80
