apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  namespace: argocd 
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: akashtamhankar/website:v7
        ports:
        - containerPort: 80
